// import Camp from "./components/Camp";
// import Features from "./components/Features";
// import GetApp from "./components/GetApp";
// import Guide from "./components/Guide";
// import Hero from "./components/Hero";

// export default function Home() {
//   return (
//     <>
//       <Hero />
//       <Camp />
//       <Guide />
//       <Features />
//       <GetApp />
//     </>
//     )
// }


"use client"
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useSession, signIn, signOut } from "next-auth/react"

const Home: NextPage = () => {
  const { data: session } = useSession()

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <div>
          <a href="#">Home</a>
          <a href="#">About</a>
          <a href="#">Contact</a>
        </div>
        <div>
          {session && session.user ? (
            <button onClick={() => signOut()}>Sign out</button>
          ) : (
            <button onClick={() => signIn()}>Sign in</button>
          )}
        </div>
      </nav>
      <main>
        <div>
          {session && session.user ? (

            <div>
              <div >
                <Image src="/architecture.png" alt="book" width={500} height={300} />
              </div>
              <div>
                <h2>Computer Programming Cookbook</h2>
                <p>
                  This is a simple hero unit, a simple jumbotron-style component for calling
                  extra attention to featured content or information.
                </p>
                <p>
                  <a href="https://nextjs.org/docs" target="_blank">
                    Learn More
                  </a>
                </p>
              </div>
            </div>
          ) : (
            <p>You need to sign in to access the books</p>
          )}
        </div>
      </main>
    </div>
  )
}

export default Home
